### ISSUE TITLE
Re-use of classes

### ISSUE THREAD

**Issue by jordanwillis** [yufeng8/TeaCozy#2]
Another way that you can greatly improve both your HTML and CSS is to re-use classes for common contexts and styles.  For example, instead of defining different class name for each of the teas of the month section, it would be better to re-use a single class name for a couple of reasons.  First, conceptually, each tea of the month section is structurally and conceptually the same (a listing that includes an image and heading.  Second, because they are conceptually the same it also turns out that they each are styled the same.  So by creating different classes for each item you complicate your HTML and fill your CSS with lots of duplication.

Here is an example using a single class.

``` html
<div class="flex-container items">
  <div class="item">
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-berryblitz.jpg" />
    <span>Fall Berry Blitz Tea</span>
  </div>
  <div class="item">
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-spiced-rum.jpg" />
    <span>Spiced Rum Tea</span>
  </div>
  <div class="item">
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-donut.jpg" />
    <span>Seasonal Donuts</span>
  </div>
  <div class="item">
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-donut.jpg" />
    <span>Myrtle Ave Tea</span>
  </div>
  <div class="item">
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-bedford-bizarre.jpg" />
    <span>Bedford Bizarre Tea</span>
  </div>
</div>
```

``` css
.item {
  padding: 5px;
}

.item img {
  height: 200px;
  margin: 10px;
  display: block;
}

.item span {
  display: block;
  padding: 5px;
  font-weight: bold;
  text-align: center;
}
```
